### ISSUE TITLE
"targetModule" should be a string - marko-hydrate error

### ISSUE THREAD

**Issue by BryceEWatson** [lasso-js/lasso-marko-taglib#10]
One of my pages is failing with the below stack:
```
Exception: Error: Failed to walk dependency [marko-hydrate:
.........
Cause: AssertionError [ERR_ASSERTION]: "targetModule" should be a string
    at module.exports (/Users/brywatson/e4csite/node_modules/lasso/node_modules/raptor-util/createError.js:7:50)
    at walkDependency (/Users/brywatson/e4csite/node_modules/lasso/src/dependency-walker.js:123:23)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
```
I added some debug logic at `lasso/src/resolve/index.js:29` and found that the below less object is coming in the `targetModule` and causing the crash:
```
{ type: 'less',
  code: '.app-terms {\n        background-color: #FFF;\n    }\n    .terms__container {\n        padding: 0px 35px 35px 35px;\n    }',
  virtualPath: './index.marko.less',
  path: './index.marko' }
```
If I remove the style from this template it will use the next less style it finds to cause the crash. This does not happen on other pages that are loading what appears to be identical ways.

I'm using `marko@4.7.5` `lasso@3.1.2` and `lasso-marko@2.4.0`

**Comment by BryceEWatson** [comment]
Note: Downgrading to `lasso-marko@2.3.1` fixes the issue, so maybe there is some other issue with latest lasso-marko?
